// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProductsSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addProduct() {
    driver.get("https://www.demoblaze.com/index.html");
    driver.manage().window().setSize(new Dimension(1082, 800));
    driver.findElement(By.cssSelector(".col-lg-4:nth-child(1) .card-img-top")).click();
    driver.findElement(By.linkText("Add to cart")).click();
    assertThat(driver.switchTo().alert().getText(), is("Product added"));
    {
      List<WebElement> elements = driver.findElements(By.id("myTabContent"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void categoryTest() {
    driver.get("https://www.demoblaze.com/index.html");
    driver.manage().window().setSize(new Dimension(1089, 800));
    vars.put("category1", "Laptops");
    System.out.println(vars.get("category1").toString());
    vars.put("category2", "Monitors");
    System.out.println(vars.get("category1").toString());
    driver.findElement(By.id("itemc")).click();
    driver.findElement(By.linkText("vars.get("category1").toString()")).click();
    driver.findElement(By.linkText("vars.get("category2").toString()")).click();
  }
  @Test
  public void confirmationTest() {
    driver.get("https://www.demoblaze.com/index.html");
    driver.manage().window().setSize(new Dimension(1085, 800));
    driver.findElement(By.id("cartur")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    vars.put("name", "arwa");
    vars.put("country", "tunisia");
    vars.put("city", "CUN");
    vars.put("card", "1");
    vars.put("month", "8");
    vars.put("year", "2024");
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys(vars.get("name").toString());
    driver.findElement(By.id("country")).click();
    driver.findElement(By.id("country")).sendKeys(vars.get("country").toString());
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys(vars.get("city").toString());
    driver.findElement(By.id("card")).click();
    driver.findElement(By.id("card")).sendKeys(vars.get("card").toString());
    driver.findElement(By.id("month")).click();
    driver.findElement(By.id("month")).sendKeys(vars.get("month").toString());
    driver.findElement(By.id("year")).click();
    driver.findElement(By.id("year")).sendKeys(vars.get("year").toString());
    driver.findElement(By.cssSelector("#orderModal .btn-primary")).click();
    driver.findElement(By.cssSelector(".confirm")).click();
  }
  @Test
  public void productListTest() {
    driver.get("https://www.demoblaze.com/index.html");
    driver.manage().window().setSize(new Dimension(1079, 800));
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("next2")).click();
    assertThat(driver.findElement(By.id("cat")).getText(), is("CATEGORIES"));
    {
      List<WebElement> elements = driver.findElements(By.id("prev2"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("next2"));
      assert(elements.size() > 0);
    }
  }
}
